"""add detail_html to home_banner

Revision ID: 1da12c60db1c
Revises: 
Create Date: 2026-05-19 09:05:16.112788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da12c60db1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_banner', schema=None) as batch_op:
        batch_op.drop_column('detail_html')

    # ### end Alembic commands ###
