"""add role to miniapp_user

Revision ID: 7ee5ae0c7bb2
Revises: 9e1f2a3b4c5d
Create Date: 2026-05-25 14:59:32.064252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ee5ae0c7bb2'
down_revision = '9e1f2a3b4c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('submit_image_url', sa.String(length=512), nullable=True),
    sa.Column('submit_description', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_showcase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['miniapp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_tag_rel')
    with op.batch_alter_table('product_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('product_tag')
    with op.batch_alter_table('miniapp_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('product_type',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'礼盒'"))
        batch_op.alter_column('list_category',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('primary_category',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('process_text',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=32),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('fk_product_publisher_user_id_miniapp_user'), type_='foreignkey')
        batch_op.drop_column('want_qrcode_url')
        batch_op.drop_column('publisher_user_id')
        batch_op.drop_column('view_count')

    with op.batch_alter_table('product_flow_step', schema=None) as batch_op:
        batch_op.alter_column('step_order',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_flow_step', schema=None) as batch_op:
        batch_op.alter_column('step_order',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('publisher_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('want_qrcode_url', mysql.VARCHAR(length=512), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_publisher_user_id_miniapp_user'), 'miniapp_user', ['publisher_user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('process_text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('primary_category',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('list_category',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('product_type',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'礼盒'"))
        batch_op.alter_column('summary',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('miniapp_user', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.create_table('product_tag',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('product_tag_rel',
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('product_tag_rel_ibfk_1')),
    sa.ForeignKeyConstraint(['tag_id'], ['product_tag.id'], name=op.f('product_tag_rel_ibfk_2')),
    sa.PrimaryKeyConstraint('product_id', 'tag_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_task')
    # ### end Alembic commands ###
